# Generated by Django 4.1.2 on 2022-11-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=150)),
                ('age', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('status', models.BooleanField(choices=[(1, 'Active'), (0, 'Inactive')], default=False)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
    ]
